### ISSUE TITLE
desec.io: ipv4 gets set automatically even with v4: false

### ISSUE THREAD

**Issue by simon-kolkmann** [simon-lorenz/dyngo#1]
```yaml
  # config.yaml
  desec:
    username: "me.dedyn.io"
    password: "<pw>"
    domains:
      - name: "dyngo.me.dedyn.io"
        v4: false
        v6: true 
```

This will automatically create an A record containing the ip from which the request originated.
